name: sid-CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: [ '5432:5432' ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.10
    - name: Copiar configurações .env
      run: |
        cp contrib/env-sample .env
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv sync
    - name: Executar flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names 
        pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics 
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide 
        pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
